@extends('layout.main')
@section('title', 'PalHire')
@section('content')
    @include('website.partials.slider')
    @include('website.partials.support_company')
    @include('website.partials.online_cv_area')
    @include('website.partials.support_company2')
    @include('website.partials.apply_process')
    @include('website.partials.contact')
@endsection
